/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easymanagehotel;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.function.BiConsumer;
import java.util.function.Function;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author daniel
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    FileManager roomFile;
    FileManager viewFile;
    FileManager isAvailableFile;
    FileManager typeFile ;
    FileManager currentOwnerFile;
    FileManager timeLeftFile;
    
    List<Room> rooms;    
    Map<Integer, Room> roomsByNumber;
    
    public GUI() {
        initComponents();
        
        try {
            
            roomFile = new FileManager("rooms.txt");
            viewFile = new FileManager("views");
            isAvailableFile = new FileManager("isAvailable.txt");
            typeFile = new FileManager("types.txt");
            currentOwnerFile = new FileManager("currentOwners.txt");
            timeLeftFile = new FileManager("timeLefts.txt");
            
            List<String> roomNumbersString = roomFile.readFile();
            List<String> views = viewFile.readFile();
            List<String> types = typeFile.readFile();
            List<String> isAvailablesString = isAvailableFile.readFile();
            List<String> currentOwners = currentOwnerFile.readFile();
            List<Integer> roomNumbers = new ArrayList();
            List<Boolean> isAvailables = new ArrayList();
            List<String> timeLefts = timeLeftFile.readFile();
            
            for(String roomNumberString: roomNumbersString) {
                int roomNumber = Integer.parseInt(roomNumberString);
                roomNumbers.add(roomNumber);                
            }
            for(String isAvailableString: isAvailablesString) {
                if(isAvailableString.equals("true")) {
                    isAvailables.add(true);
                } else {
                    isAvailables.add(false);
                }
            }
            
//            rooms = new ArrayList();
            for(int i = 0; i < roomNumbers.size(); i++) {
                
                int roomNumber = roomNumbers.get(i);
                String type = types.get(i);
                String view = views.get(i);
                boolean isAvailable = isAvailables.get(i);
                String currentOwner = currentOwners.get(i);
                String timeLeft = timeLefts.get(i);
                Room room = new Room(roomNumber, type, view, currentOwner, timeLeft, isAvailable);
                rooms.add(room);
            }
            for (Room r: rooms) {
                roomsByNumber.put(r.getNumber(), r);
            }
    }   catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomsArrangmentDialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        roomsTextArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        newRoomNumberTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        roomViewTextField = new javax.swing.JTextField();
        roomTypeTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        roomNumberTextLabel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ownerNameTextLabel = new javax.swing.JTextField();
        rentTimeTextLabel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rentButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        roomsTextArea.setColumns(20);
        roomsTextArea.setRows(5);
        jScrollPane1.setViewportView(roomsTextArea);

        jLabel6.setFont(new java.awt.Font("Adobe Fan Heiti Std", 0, 24)); // NOI18N
        jLabel6.setText("add a room:");

        jLabel7.setFont(new java.awt.Font("Adobe Fan Heiti Std", 0, 24)); // NOI18N
        jLabel7.setText("room number:");

        newRoomNumberTextField.setFont(new java.awt.Font("Adobe Fan Heiti Std", 0, 24)); // NOI18N
        newRoomNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRoomNumberTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Adobe Fan Heiti Std", 0, 24)); // NOI18N
        jLabel8.setText("room type:");

        jLabel9.setFont(new java.awt.Font("Adobe Fan Heiti Std", 0, 24)); // NOI18N
        jLabel9.setText("room view");

        roomViewTextField.setFont(new java.awt.Font("Adobe Fan Heiti Std", 0, 24)); // NOI18N

        roomTypeTextField.setFont(new java.awt.Font("Adobe Fan Heiti Std", 0, 24)); // NOI18N

        addButton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        addButton.setText("add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newRoomNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roomTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(roomViewTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(newRoomNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(roomViewTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roomTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout roomsArrangmentDialogLayout = new javax.swing.GroupLayout(roomsArrangmentDialog.getContentPane());
        roomsArrangmentDialog.getContentPane().setLayout(roomsArrangmentDialogLayout);
        roomsArrangmentDialogLayout.setHorizontalGroup(
            roomsArrangmentDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        roomsArrangmentDialogLayout.setVerticalGroup(
            roomsArrangmentDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomsArrangmentDialogLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Easy Manage - Makes your life easier everyday");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel2.setText("rent a room:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText("room number: ");

        roomNumberTextLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel4.setText("Owner's name:");

        ownerNameTextLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        rentTimeTextLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel5.setText("check out time:");

        rentButton.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        rentButton.setText("Rent");
        rentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentButtonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton1.setText("arrange rooms");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roomNumberTextLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ownerNameTextLabel)
                                    .addComponent(rentTimeTextLabel)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 451, Short.MAX_VALUE)
                        .addComponent(rentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(418, 418, 418))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(522, 522, 522))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(roomNumberTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ownerNameTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rentTimeTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentButtonActionPerformed
        if(this.roomNumberTextLabel.getText().isEmpty() || 
                this.ownerNameTextLabel.getText().isEmpty() || 
                this.rentTimeTextLabel.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "You must show all fields");
        } else {
            int roomNumber = Integer.parseInt(this.roomNumberTextLabel.getText());
            String currentOwner = this.ownerNameTextLabel.getText();
            String rentTime = this.rentTimeTextLabel.getText();
            roomsByNumber.get(roomNumber).setCurrentOwner(currentOwner);
            roomsByNumber.get(roomNumber).setTimeLeft(rentTime);
            
        }
    }//GEN-LAST:event_rentButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if(this.newRoomNumberTextField.getText().isEmpty() ||
                this.roomTypeTextField.getText().isEmpty() ||
                this.roomViewTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Must fill all fiels");
            
        } else {
             int roomNumber = Integer.parseInt(this.newRoomNumberTextField.getText());
             String type = this.roomTypeTextField.getText();
             String view = this.roomViewTextField.getText();
             
             Room room = new Room(roomNumber, type, view);
             rooms.add(room);
             roomsByNumber.put(room.getNumber(), room);
             
             this.roomFile.write(""+room.getNumber());
             this.typeFile.write(room.getType());
             this.viewFile.write(room.getView());
             if(room.isIsAvailable()) {
                 this.isAvailableFile.write("true");
             } else {
                 this.isAvailableFile.write("false");
             }
             this.currentOwnerFile.write(room.getCurrentOwner());
             this.timeLeftFile.write(room.getTimeLeft());
             this.roomsTextArea.setText(this.roomsTextArea.getText()+"\n" + room.getNumber() +
                     " : " + room.getType()+" , " +room.getView()+ " , "+room.getCurrentOwner()+ " , "+
                     room.getTimeLeft()+ " , "+"true");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void newRoomNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRoomNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newRoomNumberTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField newRoomNumberTextField;
    private javax.swing.JTextField ownerNameTextLabel;
    private javax.swing.JButton rentButton;
    private javax.swing.JTextField rentTimeTextLabel;
    private javax.swing.JTextField roomNumberTextLabel;
    private javax.swing.JTextField roomTypeTextField;
    private javax.swing.JTextField roomViewTextField;
    private javax.swing.JDialog roomsArrangmentDialog;
    private javax.swing.JTextArea roomsTextArea;
    // End of variables declaration//GEN-END:variables
}
